### ISSUE TITLE
Pacman: named pipes

### ISSUE THREAD

**Issue by Lucasvo1** [Lucasvo1/FHVGame#49]

**Comment by Lucasvo1** [comment]
There have been several people which have succesfully used named pipes inside Unity but as it seems it does not work very well. The code for the named pipes compiles in Mono but only Unity does not find the Pipes namespace (http://answers.unity3d.com/questions/483123/how-do-i-get-named-pipes-to-work-in-unity.html) . I will be trying other ways to make them work but maybe we should look at other alternatives (e.g. UDP, TCP).

**Comment by Lucasvo1** [comment]
Change the version of .NET inside Unity to the full .NET library instead of just the subset.

**Comment by tme5092** [comment]
not relevant anymore
